title: "PowerBi Analytics"
description: "User Analysis Across Multiple Social Media"
theme: jekyll-theme-midnight

# Enable GitHub Pages features
plugins:
  - jekyll-remote-theme

# Build settings
highlighter: rouge

# Include README as homepage
include:
  - README.md
